### ISSUE TITLE
code of conduct :sparkles:

### ISSUE THREAD

**Issue by tloth** [fac-17/week-7-langs#22]
You have a wonderful code of conduct (maybe lacking "Hydrate your friends!), and a little birdie told me that you actually followed the main principles!

Swapping pairs is difficult, especially when you are on the edge of a cosy little rabbit hole, but you DID IT and I am very proud. Great improvement from last week, well done.

![great job](https://66.media.tumblr.com/63022f71af2bc26332856a96a9d82ea8/tumblr_inline_mzb5v0Sp5t1s8x9ng.gif)

**Comment by samjam48** [comment]
Agreed. You implemented this amazingly!
